name: flutter_app_template
description: Flutter template project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.6
  quiver: ^3.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_easyrefresh: ^2.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2
  kooboo_flutter_app_upgrade: ^0.0.7
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^3.3.0
  flutter_login_facebook: ^1.4.1
  permission_handler: ^9.2.0
  gallery_saver: ^2.3.2
  image_cropper: ^2.0.3
  video_compress: ^3.1.1
  wechat_assets_picker: ^7.3.2
  wechat_camera_picker: ^3.4.0
  flutter_image_compress: ^1.1.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  waterfall_flow: ^3.0.2
  webview_flutter: ^3.0.4
  flutter_swiper_null_safety: ^1.0.2
  photo_view: ^0.14.0
  flutter_html: ^3.0.0-alpha.5
  flutter_rating_bar: ^4.0.1
  tuple: ^2.0.0
  fluwx: ^3.9.0+2
  cupertino_icons: ^1.0.2
  flutter_app_badger: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
