name: flutter_app_template
description: Flutter template project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  dio: ^4.0.6
  quiver: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_easyrefresh: ^2.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  kooboo_flutter_app_upgrade: ^0.0.9
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^6.1.2
  flutter_login_facebook: ^1.4.1
  permission_handler: ^10.2.0
  image_cropper: ^8.0.2
  video_compress: ^3.1.3
  wechat_assets_picker: ^8.7.0
  wechat_camera_picker: ^4.3.2
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.0
  waterfall_flow: ^3.0.2
  webview_flutter: ^3.0.4
  photo_view: ^0.14.0
  flutter_html: ^3.0.0-beta.2
  flutter_rating_bar: ^4.0.1
  tuple: ^2.0.0
  fluwx: ^4.5.5
  flutter_app_badger: ^1.4.0
  carousel_pro_nullsafety: ^2.0.0
  rammus: ^2.5.1
  image_gallery_saver_plus: ^3.0.5
  android_id: ^0.0.7
  package_by_walle: ^1.0.2
  weibo_kit: ^4.0.0
  tencent_kit: ^4.0.0
  tobias: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
