const enUs = <String, String>{
  'login': 'Log in',
  'login_by_wechat': 'Continue with Wechat',
  'login_by_apple': 'Continue with Apple',
  'login_by_facebook': 'Continue with Facebook',
  'login_by_google': 'Continue with Google',
  'login_name_hint': 'Mobile Number',
  'login_get_sms': 'Get Verification Code',
  'login_no_get_sms': 'Re-acquisition after %s',
  'login_input_sms_hint': 'Input Code',
  'linear_gradient_or': 'OR',
  'login_success': 'login successful',
  'tab_home': 'Home',
  'tab_global_purchasing': 'CrossBorder',
  'tab_cash': 'Cash',
  'tab_personal': 'Account',
  'camera_per_dialog':
      'You need to enable the camera permission, do you want to enable it?',
  'photo_cut': 'Crop',
  'photo_shot': 'Shoot',
  'photo_select': 'Choose from album',
  'local_save_dialog':
      'You need to enable storage permission, do you want to enable it?',
  'camera_confirm': 'Send',
  'camera_shooting_tips': 'Tap to take photo.',
  'camera_shooting_with_recording_tips':
      'Tap to take photo. Long press to record video.',
  'camera_shooting_only_recording_tips': 'Long press to record video.',
  'camera_shooting_tap_recording_tips': 'Tap to record video.',
  'camera_load_failed': 'Load failed',
  'camera_action_manually_focus_hint': 'manually focus',
  'camera_action_preview_hint': 'preview',
  'camera_action_record_hint': 'record',
  'camera_action_shoot_hint': 'take picture',
  'camera_action_shooting_button_tooltip': 'shooting button',
  'camera_action_stop_recording_hint': 'stop recording',
};
